// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3NCCrLKS4jcIQyC6gwPzDmu6KhvDSPPU',
    appId: '1:1050635734306:web:91164ee7485fd80ab4e97b',
    messagingSenderId: '1050635734306',
    projectId: 'fireauth-a58b1',
    authDomain: 'fireauth-a58b1.firebaseapp.com',
    storageBucket: 'fireauth-a58b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB25AcVT02uko3tgdB-i0_8yC_B7GkzgZc',
    appId: '1:1050635734306:android:6d31ce51a90ec5c7b4e97b',
    messagingSenderId: '1050635734306',
    projectId: 'fireauth-a58b1',
    storageBucket: 'fireauth-a58b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ZwTe4WGWAzFTmFT-W5VTH4USvc8Kx_8',
    appId: '1:1050635734306:ios:b33dc758152e54efb4e97b',
    messagingSenderId: '1050635734306',
    projectId: 'fireauth-a58b1',
    storageBucket: 'fireauth-a58b1.appspot.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ZwTe4WGWAzFTmFT-W5VTH4USvc8Kx_8',
    appId: '1:1050635734306:ios:b33dc758152e54efb4e97b',
    messagingSenderId: '1050635734306',
    projectId: 'fireauth-a58b1',
    storageBucket: 'fireauth-a58b1.appspot.com',
    iosBundleId: 'com.example.fireauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3NCCrLKS4jcIQyC6gwPzDmu6KhvDSPPU',
    appId: '1:1050635734306:web:b774b95a73bf6341b4e97b',
    messagingSenderId: '1050635734306',
    projectId: 'fireauth-a58b1',
    authDomain: 'fireauth-a58b1.firebaseapp.com',
    storageBucket: 'fireauth-a58b1.appspot.com',
  );
}
